---
title: Lux
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
SEOTitle: Lux by Art
header-img: img/home-bg.jpg
email: 
description: This is my site.
keyword: 
url: 
baseurl: "/welcome"
RSS: false
weibo_username: 
zhihu_username: 
github_username: 
facebook_username: 
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
anchorjs: true
gems:
- jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
duoshuo_username: 
duoshuo_share: false
ba_track_id: " "
ga_track_id: " "
ga_domain: 
sidebar: true
sidebar-about-description: 'This is my information. '
sidebar-avatar: "/img/avatar-hux.jpg"
featured-tags: true
featured-condition-size: 1
friends:
- title: Foo
  href: "#"
- title: Foo
  href: "#"
- title: Bar
  href: "#"
- title: Example Friends
  href: "#"
- title: It helps SEO
  href: "#"
