---
title: Your Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
SEOTitle: 你的博客 | Your Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: ''
keyword: ''
url: http://huangxuan.me
baseurl: "/huxblog-boilerplate"
RSS: false
weibo_username: huxpro
zhihu_username: huxpro
github_username: huxpro
facebook_username: huxpro
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
anchorjs: true
gems:
- jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
duoshuo_username: huxblog
duoshuo_share: true
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
ga_track_id: UA-49627206-1
ga_domain: huangxuan.me
sidebar: true
sidebar-about-description: 写写代码，做做设计，看看产品。世界那么大，多玩玩看看。
sidebar-avatar: "/img/avatar-hux.jpg"
featured-tags: true
featured-condition-size: 1
friends:
- title: Hux Blog
  href: http://huangxuan.me
- title: Foo
  href: "#"
- title: Bar
  href: "#"
- title: Example Friends
  href: "#"
- title: It helps SEO
  href: "#"
